name: Generate Emoji List

on:
  workflow_dispatch:

jobs:
  generate_emoji_list:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
            repository: microsoft/fluentui-emoji
            token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
            path: fluentui-emoji

      - uses: actions/checkout@v3
        with:
          path: cdn

      - name: Set Up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run generate_emoji_list.py
        run: python cdn/scripts/generate_emoji_list.py

      - name: Push to github.com/malte9799/cdn
        run: |
          cd cdn
          git config user.name github-actions[bot]
          git config user.email github-actions@github.com
          git add fluentui-emoji-list.json
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update fluentui-emoji-list.json"
            git push
          fi